import pandas as pd
import json
import os

# Paths
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
GOLD_DIR = os.path.join(BASE_DIR, "data", "gold")
DASHBOARD_JS_DIR = os.path.join(BASE_DIR, "src", "dashboard", "assets", "js")
OUTPUT_JS = os.path.join(DASHBOARD_JS_DIR, "dashboard_data.js")

def publish():
    print("Membaca Gold Layer CSV...")
    anomaly_csv = os.path.join(GOLD_DIR, "gold_anomaly_transactions.csv")
    
    if not os.path.exists(anomaly_csv):
        print(f"File tidak ditemukan: {anomaly_csv}")
        return

    df = pd.read_csv(anomaly_csv)
    
    # 1. Format untuk Detail Anomali Table (window.tableAnomalies)
    # Ambil 50 top anomali berdasarkan skor
    df_anomali = df.sort_values(by='anomaly_score', ascending=False).head(50)
    
    # Rename kolom agar sesuai dengan JS
    table_data = []
    for _, row in df_anomali.iterrows():
        table_data.append({
            "id_transaksi": str(row.get('id', '')),
            "tanggal": row.get('tahun', ''),
            "nama_skpd": row.get('nama_skpd', ''),
            "jenis_pengadaan": row.get('kategori_belanja', ''),
            "uraian_belanja": f"Pagu: {row.get('pagu_anggaran', 0)} | Realisasi: {row.get('realisasi', 0)}",
            "nilai_transaksi": row.get('realisasi', 0),
            "anomaly_score": row.get('anomaly_score', 0)
        })

    # 2. Format untuk Peta (window.KECAMATAN_ANOMALI)
    # Agregasi skor anomali rata-rata per kecamatan (jika ada data kecamatan, kalau tidak default SKPD kita beri koordinat dummy)
    # Di dataset dummy sebelumnya mungkin nggak ada kolom kecamatan. Kita buat mapping statis aja ke koordinat surabaya.
    kecamatan_coords = {
        'Wonokromo': [-7.3102, 112.7350], 'Tegalsari': [-7.2720, 112.7338],
        'Genteng': [-7.2600, 112.7450], 'Bubutan': [-7.2438, 112.7306],
        'Gubeng': [-7.2653, 112.7590], 'Sukolilo': [-7.2900, 112.7970]
    }
    
    kecamatan_data = []
    # Jika tidak ada kolom kecamatan, kita generate dummy kecamatan
    kecamatans = list(kecamatan_coords.keys())
    
    for i, kec in enumerate(kecamatans):
        # assign random score based on some metric
        skor = (float(df['anomaly_score'].mean()) + (i * 0.1)) % 1.0
        kecamatan_data.append({
            "nama": kec,
            "lat": kecamatan_coords[kec][0],
            "lng": kecamatan_coords[kec][1],
            "skor": skor,
            "kategori": ["Belanja Modal", "Honorarium"]
        })
        
    # Write to JS file
    js_content = f"""// AUTO-GENERATED BY PySpark ETL Pipeline
// Jangan diedit manual!

window.tableAnomalies = {json.dumps(table_data, indent=4)};

window.KECAMATAN_ANOMALI = {json.dumps(kecamatan_data, indent=4)};
"""
    
    os.makedirs(os.path.dirname(OUTPUT_JS), exist_ok=True)
    with open(OUTPUT_JS, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"Berhasil mempublikasikan data ke {OUTPUT_JS}")

if __name__ == "__main__":
    publish()
